import React from "react";
import Auth_wrapper from "@/components/Auth/Auth_wrapper";
import Head from "next/head";


const Auth = () => {
    return (
        <>
            <Head>
                <title>Authentication</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Auth_wrapper/>
        </>
    );
};

export default Auth;