import Head from 'next/head'
import React, {useEffect} from "react";
import styles from "./../styles/Home.module.scss"
import Parallax_scenery from "@/components/Frames/Parallax-scenery/Parallax_scenery";
import Choose_site_type from "@/components/Frames/Choose-site-type/Choose_site_type";
import Technologies from "@/components/Frames/Technologies/Technologies";
import Time_trap_home from "@/components/Frames/Time-trap-home/Time_trap_home";
import {Footer} from "@/components/Footer/Footer";
import {Header} from "@/components/Header/Header";


/*export const getStaticProps = async () => {
    const res = await fetch('https://api.publicapis.org/entries');
    const data = await res.json();

    return {
        props: data
    };
};*/

export default function Home() {


  return (
    <>
      <Head>
        <title>Wanna my site</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header/>
      <main className={styles.Home}>
        <Parallax_scenery/>
        <Choose_site_type/>
        <Technologies/>
        <Time_trap_home/>
      </main>
        <Footer/>
    </>
  )
}
